platform:ios, '7.0'

pod 'Tracking', :path => '../Tracking'

source 'https://github.com/CocoaPods/Specs.git'

pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTNetwork',
    'RCTWebSocket'
]
